config/routes.rb
require 'sidekiq/web'

ServiceProviderPortal::Application.routes.draw do

  ActiveAdmin.routes(self)

  resources :search, only: :index

  resources :companies, only: [:show, :edit, :update] do
    resources :alerts
    resources :discounts
    resources :users
    resources :company_admins, path: 'users', controller: :users
    resources :administrators, path: 'users', controller: :users
  end

  resource  :account, only: [:show, :edit, :update]

  resources :password_resets, only: [:new, :create, :show, :update],
    constraints: { id: /[a-zA-Z0-9\-_]{12}/ }
  resources :activate, only: [:new, :create, :show, :update], controller: :user_activation,
    constraints: { id: /[a-zA-Z0-9\-_]{12}/ }

  resource :session, only: [:create]

  scope controller: :sessions do
    get :login,  action: :new,     as: :login
    get :logout, action: :destroy, as: :logout
  end

  constraints(proc { |req| uid = req.session[:user_id] and User.find(uid).is_a?(Administrator) }) do
    get '/debug/:action', controller: :debug
    mount Sidekiq::Web => '/sidekiq'
  end

  scope '/follow_us_on', as: :follow_us_on do
    get 'twitter',  to: redirect('https://twitter.com/#!/trustmaster')
    get 'facebook', to: redirect('https://www.facebook.com/pages/Trust-Master/165946716770592')
  end


  root :to => 'search#index'

  get '*slug', controller: :pages, action: :show, as: :page, constraints: RoutingConstraints::Pages
end

app/models/company.rb
# == Schema Information
#
# Table name: companies
#
#  id                                 :integer          not null, primary key
#  active                             :boolean          default(FALSE), not null
#  visible                            :boolean          default(FALSE), not null
#  deleted_at                         :datetime
#  deleted_by_user_id                 :integer
#  name                               :string(255)
#  email                              :string(255)
#  phone_main                         :string(255)
#  phone_mobile                       :string(255)
#  phone_fax                          :string(255)
#  website_url                        :string(255)
#  in_business_since                  :date
#  about                              :string(255)
#  benefits                           :text
#  specialty                          :text
#  offers_24_hour_service             :boolean          default(FALSE), not null
#  offers_emergency_service           :boolean          default(FALSE), not null
#  insured                            :boolean          default(FALSE), not null
#  insurance_state_id                 :integer
#  insurance_valid_from               :date
#  insurance_valid_until              :date
#  created_at                         :datetime         not null
#  updated_at                         :datetime         not null
#  insurance_certificate_file_name    :string(255)
#  insurance_certificate_content_type :string(255)
#  insurance_certificate_file_size    :integer
#  insurance_certificate_updated_at   :datetime
#  insurance_certificate_fingerprint  :string(255)
#  insurance_certificate_meta         :text
#  description                        :text
#

class Company < ActiveRecord::Base
  include CompanyActivationRequirements
  extend EasyArelAccess

  attr_accessor :current_sections
  paginates_per 5

  ### Associations
  has_many :affiliations, dependent: :destroy
  has_many :associations, dependent: :destroy
  has_many :certifications, dependent: :destroy

  has_many :discounts, -> { includes(:type) }, dependent: :destroy

  has_many :locations, -> { includes(:state, :country) }, dependent: :destroy

  has_many :company_categories, -> { includes(sub_category: :category) }, dependent: :destroy
  has_many :company_service_areas, -> { includes(service_area: :market) }, dependent: :destroy

  has_many :business_licenses, -> { includes(:issuing_state) }, dependent: :destroy
  has_many :personal_licenses, -> { includes(:issuing_state) }, dependent: :destroy
  # this should be has_one, but, due to quirks, it's not (see below)
  has_many :business_filings, -> { includes(:issuing_state).limit(1).order(:updated_at) }, dependent: :destroy

  has_many :sub_categories, -> { uniq.readonly }, through: :company_categories
  has_many :categories, -> { uniq.readonly }, through: :sub_categories

  has_many :service_areas, -> { uniq.readonly.includes(:market) }, through: :company_service_areas
  has_many :markets, -> { uniq.readonly.includes(:service_areas) }, through: :service_areas

  has_many :users, dependent: :destroy

  belongs_to :insurance_state, class_name: 'State'

  belongs_to :deleted_by_user, class_name: 'User'

  ### Nested Attributes

    accepts_nested_attributes_for :affiliations, :associations, :certifications,
      allow_destroy: true,
      reject_if: proc { |attributes|
        attributes.values_at(:name, :title).all?(&:blank?)
      }

    accepts_nested_attributes_for :locations,
      allow_destroy: true,
      reject_if: proc { |attributes|
        attributes.values_at(:city, :zip).all?(&:blank?)
      }

    accepts_nested_attributes_for :business_licenses, :personal_licenses, :business_filings,
      allow_destroy: true,
      reject_if: proc { |attributes|
        attributes.has_key?(:id) or attributes.values_at(:number, :issuing_state_id).all?(&:blank?)
      }

    accepts_nested_attributes_for :company_service_areas, :company_categories,
      allow_destroy: true

  ### Uploaders
    has_attached_file :insurance_certificate

  ### Attribute Normalizers
    normalize_attributes :phone_main, :phone_mobile, :phone_fax, with: :phone_number
    normalize_attributes :website_url, :about, :benefits, :description, :specialty

  ### Callbacks
    before_validation :nullify_insurance_fields_if_necessary
    set_callback(:post_process, :before) do
      !! ValidationPatterns::ImageContentTypes.match(insurance_certificate.content_type)
    end
    before_save :set_active_flag

  ### Validations
    with_options if: :insured do |user|
      user.validates :insurance_state,       presence: true
      user.validates :insurance_valid_from,  presence: true, date: { in_past: true }
      user.validates :insurance_valid_until, presence: true, date: { in_future: true }
      user.validates_attachment :insurance_certificate, presence: true,
        size: {
          less_than_or_equal_to: 1.megabytes,
          allow_blank: true },
        content_type: {
          content_type: ValidationPatterns::AcceptableUploadTypes,
          allow_blank: true }
    end
    validates :name, :email, :phone_main, :phone_mobile, :phone_fax, :website_url, :about,
      length: { maximum: 255 }, allow_blank: true
    validates :name, uniqueness: true, presence: true
    validates :phone_fax, :phone_main, :phone_mobile, phone: true, allow_blank: true
    validates :email, email: true, allow_blank: true
    validates :in_business_since, date: { in_past: true }, allow_blank: true
    validates :website_url, url: true, allow_blank: true

  ### Attribute Protection
    attr_accessible :name, :email, :phone_main, :phone_mobile, :phone_fax, :website_url,
      :in_business_since, :about, :description, :specialty, :offers_24_hour_service,
      :offers_emergency_service, :insured, :insurance_state_id, :insurance_certificate,
      :insurance_valid_from, :insurance_valid_until, :benefits, as: [:user, :company_admin, :administrator]
    attr_accessible :affiliations_attributes, :associations_attributes, :certifications_attributes,
      :locations_attributes, :business_licenses_attributes, :personal_licenses_attributes,
      :business_filings_attributes, :company_service_areas_attributes,
      :company_categories_attributes, :discounts_attributes, as: [:user, :company_admin, :administrator]

    attr_accessible :visible, as: :administrator

  ### Scopes
    # scope :any_text_field_contains, lambda { |query|
    #   ids = CompanySearch.basic_search(query).pluck(:company_id)
    #   where(id: ids.uniq)
    # }

    scope :active,  -> { where(active: true) }
    scope :visible, -> { where(visible: true) }

    # default_scope includes(:locations, :company_categories, :company_service_areas)
    scope :sorted, -> { order(t[:updated_at].desc) } # this may need to be looked at later

  ### Instance Methods
    delegate :name, to: :insurance_state, prefix: true

    # Show the company name in the URL
    def to_param
      [id, read_attribute(:name).parameterize].join('-')
    end

    # since I was having trouble bending the has_one to my will (specifically, allowing for only
    # delete/create/replace operations on it), I opted to use (has_many, limit: 1), so this will
    # return that one record (or nil), using the singular name.
    def business_filing
      business_filings.first
    end

    def primary_location_name
      locations.first.try(:name)
    end

    def in_business_since=(string)
      if year = string.presence.try{|s| s = s.to_i; s > 1700 ? s : nil }
        date = Date.new(year)
      else
        date = nil
      end
      write_attribute(:in_business_since, date)
    end

    def phone_numbers
      Hash.new.tap do |numbers|
        numbers[:phone_main]   = phone_main   if phone_main?
        numbers[:phone_mobile] = phone_mobile if phone_mobile?
        numbers[:phone_fax]    = phone_fax    if phone_fax
      end
    end

    def all_licenses
      self.business_licenses + self.personal_licenses
    end

  private

    # the form simply hides the insurance fields when the user says "No". this will actually nullify
    # the respective collumns unless #insured is truthy
    def nullify_insurance_fields_if_necessary
      return if self[:insured]
      self[:insurance_state_id]    = nil
      self[:insurance_valid_from]  = nil
      self[:insurance_valid_until] = nil
      self.insurance_certificate = nil
      return true
    end

    def set_active_flag
      self[:active] = can_be_activated?
      return true
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  respond_to :html, :json

  # defaults resource_class: Company, collection_name: 'companies'
  # actions :index

  authorize_resource :company_search

  def index
    @search = SearchQuery.new(params.fetch(:search_query, {}))

    respond_to do |format|
      format.html do
        if params.key?(:search_query)
          render :search
        else
          render :index
        end
      end
    end
  end

  protected

    def collection
      @companies ||= @search.companies.accessible_by(current_ability).uniq(true).page(params[:page])
    end
    helper_method :collection

    def popular_categories
      @popular_categories ||= SubCategory.order('companies_count DESC').limit(8).includes(:category)
    end
    helper_method :popular_categories
end

app/views/search/_buyers_guide_welcome.haml
= cache :buyers_guide_welcome do
  .tabs.welcome-messages{class: 'ui-tabs ui-helper-reset ui-widget-content ui-wigdet ui-corner-all'}
    %ul.nav.tab_bar{class: 'ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-wigdet-header ui-corner-all'}
      - [:listing, :capabilities, :credentials, :discounts].each do |label|
        %li.ui-state-default.ui-corner-top
          = link_to t(".tabs.#{label}.name"), "##{label}"
      %li.ui-state-default.ui-corner-top
        = link_to t(".tabs.reviews.name"), "#reviews", class: 'disabled'

    .tab#listing=      format_as_markdown(t('.tabs.listing.content'))
    .tab#capabilities= format_as_markdown(t('.tabs.capabilities.content'))
    .tab#credentials=  format_as_markdown(t('.tabs.credentials.content'))
    .tab#discounts=    format_as_markdown(t('.tabs.discounts.content'))
    .tab#reviews=      format_as_markdown(t('.tabs.reviews.content'))
    .tab#initial
      = image(:preferred_provider_seal, class: 'float-left')
      = format_as_markdown(t('.tabs.initial.content'))

app/views/search/_form.haml
= simple_form_for(@search, url: search_index_path, method: :get, wrapper: :search, html: {id: :company_search}) do |form|
  .search_wrap
    = form.input :query, as: :search
    = form.button :submit
  .filter
    = form.input :category_ids, as: :grouped_select, collection: Category.includes(:sub_categories).all, group_method: :sub_categories, skip_hidden_field: true, input_html: { multiple: true }

app/views/search/_popular_categories.haml
= cache(:popular_categories) do
  #popular_categories
    %h3= t('.header', count: popular_categories.count)

    .popular_categories
      - popular_categories.group_by(&:category).each do |category, sub_categories|
        - sub_categories.each do |sub_category|
          %div[sub_category]
            = link_to search_index_path('search_query[category_ids][]' => sub_category.id) do
              #{sub_category.category_name} - #{sub_category.name}
              / (#{sub_category.companies_count})

app/views/search/index.haml
- title t('.title')
- content_for :content_div_class, 'col-2-wide'

#col-a
  = render 'form'

  = render 'popular_categories', popular_categories: popular_categories

%h2.secondary-title= t('.secondary_title')

#col-b
  #company_details= render 'buyers_guide_welcome'

app/views/search/search.haml
- title t('.title')
- content_for :content_div_class, 'col-2-wide'

#col-a
  = render 'form'

  - if collection.total_count > 0
    .results
      %h4= t('.results_count', count: collection.total_count)

      = paginate collection

      %ul.companies
        = render collection

  .footer
    = paginate collection
    .search_summary= page_entries_info(collection, entry_name: Company.model_name.human)


%h2.secondary-title= t('.secondary_title')

#col-b
  #company_details= render 'buyers_guide_welcome'