config/routes.rb
require 'sidekiq/web'

ServiceProviderPortal::Application.routes.draw do

  ActiveAdmin.routes(self)

  resources :search, only: :index

  resources :companies, only: [:show, :edit, :update] do
    resources :alerts
    resources :discounts
    resources :users
    resources :company_admins, path: 'users', controller: :users
    resources :administrators, path: 'users', controller: :users
  end

  resource  :account, only: [:show, :edit, :update]

  resources :password_resets, only: [:new, :create, :show, :update],
    constraints: { id: /[a-zA-Z0-9\-_]{12}/ }
  resources :activate, only: [:new, :create, :show, :update], controller: :user_activation,
    constraints: { id: /[a-zA-Z0-9\-_]{12}/ }

  resource :session, only: [:create]

  scope controller: :sessions do
    get :login,  action: :new,     as: :login
    get :logout, action: :destroy, as: :logout
  end

  constraints(proc { |req| uid = req.session[:user_id] and User.find(uid).is_a?(Administrator) }) do
    get '/debug/:action', controller: :debug
    mount Sidekiq::Web => '/sidekiq'
  end

  scope '/follow_us_on', as: :follow_us_on do
    get 'twitter',  to: redirect('https://twitter.com/#!/trustmaster')
    get 'facebook', to: redirect('https://www.facebook.com/pages/Trust-Master/165946716770592')
  end


  root :to => 'search#index'

  get '*slug', controller: :pages, action: :show, as: :page, constraints: RoutingConstraints::Pages
end

app/models/company.rb
# == Schema Information
#
# Table name: companies
#
#  id                                 :integer          not null, primary key
#  active                             :boolean          default(FALSE), not null
#  visible                            :boolean          default(FALSE), not null
#  deleted_at                         :datetime
#  deleted_by_user_id                 :integer
#  name                               :string(255)
#  email                              :string(255)
#  phone_main                         :string(255)
#  phone_mobile                       :string(255)
#  phone_fax                          :string(255)
#  website_url                        :string(255)
#  in_business_since                  :date
#  about                              :string(255)
#  benefits                           :text
#  specialty                          :text
#  offers_24_hour_service             :boolean          default(FALSE), not null
#  offers_emergency_service           :boolean          default(FALSE), not null
#  insured                            :boolean          default(FALSE), not null
#  insurance_state_id                 :integer
#  insurance_valid_from               :date
#  insurance_valid_until              :date
#  created_at                         :datetime         not null
#  updated_at                         :datetime         not null
#  insurance_certificate_file_name    :string(255)
#  insurance_certificate_content_type :string(255)
#  insurance_certificate_file_size    :integer
#  insurance_certificate_updated_at   :datetime
#  insurance_certificate_fingerprint  :string(255)
#  insurance_certificate_meta         :text
#  description                        :text
#

class Company < ActiveRecord::Base
  include CompanyActivationRequirements
  extend EasyArelAccess

  attr_accessor :current_sections
  paginates_per 5

  ### Associations
  has_many :affiliations, dependent: :destroy
  has_many :associations, dependent: :destroy
  has_many :certifications, dependent: :destroy

  has_many :discounts, -> { includes(:type) }, dependent: :destroy

  has_many :locations, -> { includes(:state, :country) }, dependent: :destroy

  has_many :company_categories, -> { includes(sub_category: :category) }, dependent: :destroy
  has_many :company_service_areas, -> { includes(service_area: :market) }, dependent: :destroy

  has_many :business_licenses, -> { includes(:issuing_state) }, dependent: :destroy
  has_many :personal_licenses, -> { includes(:issuing_state) }, dependent: :destroy
  # this should be has_one, but, due to quirks, it's not (see below)
  has_many :business_filings, -> { includes(:issuing_state).limit(1).order(:updated_at) }, dependent: :destroy

  has_many :sub_categories, -> { uniq.readonly }, through: :company_categories
  has_many :categories, -> { uniq.readonly }, through: :sub_categories

  has_many :service_areas, -> { uniq.readonly.includes(:market) }, through: :company_service_areas
  has_many :markets, -> { uniq.readonly.includes(:service_areas) }, through: :service_areas

  has_many :users, dependent: :destroy

  belongs_to :insurance_state, class_name: 'State'

  belongs_to :deleted_by_user, class_name: 'User'

  ### Nested Attributes

    accepts_nested_attributes_for :affiliations, :associations, :certifications,
      allow_destroy: true,
      reject_if: proc { |attributes|
        attributes.values_at(:name, :title).all?(&:blank?)
      }

    accepts_nested_attributes_for :locations,
      allow_destroy: true,
      reject_if: proc { |attributes|
        attributes.values_at(:city, :zip).all?(&:blank?)
      }

    accepts_nested_attributes_for :business_licenses, :personal_licenses, :business_filings,
      allow_destroy: true,
      reject_if: proc { |attributes|
        attributes.has_key?(:id) or attributes.values_at(:number, :issuing_state_id).all?(&:blank?)
      }

    accepts_nested_attributes_for :company_service_areas, :company_categories,
      allow_destroy: true

  ### Uploaders
    has_attached_file :insurance_certificate

  ### Attribute Normalizers
    normalize_attributes :phone_main, :phone_mobile, :phone_fax, with: :phone_number
    normalize_attributes :website_url, :about, :benefits, :description, :specialty

  ### Callbacks
    before_validation :nullify_insurance_fields_if_necessary
    set_callback(:post_process, :before) do
      !! ValidationPatterns::ImageContentTypes.match(insurance_certificate.content_type)
    end
    before_save :set_active_flag

  ### Validations
    with_options if: :insured do |user|
      user.validates :insurance_state,       presence: true
      user.validates :insurance_valid_from,  presence: true, date: { in_past: true }
      user.validates :insurance_valid_until, presence: true, date: { in_future: true }
      user.validates_attachment :insurance_certificate, presence: true,
        size: {
          less_than_or_equal_to: 1.megabytes,
          allow_blank: true },
        content_type: {
          content_type: ValidationPatterns::AcceptableUploadTypes,
          allow_blank: true }
    end
    validates :name, :email, :phone_main, :phone_mobile, :phone_fax, :website_url, :about,
      length: { maximum: 255 }, allow_blank: true
    validates :name, uniqueness: true, presence: true
    validates :phone_fax, :phone_main, :phone_mobile, phone: true, allow_blank: true
    validates :email, email: true, allow_blank: true
    validates :in_business_since, date: { in_past: true }, allow_blank: true
    validates :website_url, url: true, allow_blank: true

  ### Attribute Protection
    attr_accessible :name, :email, :phone_main, :phone_mobile, :phone_fax, :website_url,
      :in_business_since, :about, :description, :specialty, :offers_24_hour_service,
      :offers_emergency_service, :insured, :insurance_state_id, :insurance_certificate,
      :insurance_valid_from, :insurance_valid_until, :benefits, as: [:user, :company_admin, :administrator]
    attr_accessible :affiliations_attributes, :associations_attributes, :certifications_attributes,
      :locations_attributes, :business_licenses_attributes, :personal_licenses_attributes,
      :business_filings_attributes, :company_service_areas_attributes,
      :company_categories_attributes, :discounts_attributes, as: [:user, :company_admin, :administrator]

    attr_accessible :visible, as: :administrator

  ### Scopes
    # scope :any_text_field_contains, lambda { |query|
    #   ids = CompanySearch.basic_search(query).pluck(:company_id)
    #   where(id: ids.uniq)
    # }

    scope :active,  -> { where(active: true) }
    scope :visible, -> { where(visible: true) }

    # default_scope includes(:locations, :company_categories, :company_service_areas)
    scope :sorted, -> { order(t[:updated_at].desc) } # this may need to be looked at later

  ### Instance Methods
    delegate :name, to: :insurance_state, prefix: true

    # Show the company name in the URL
    def to_param
      [id, read_attribute(:name).parameterize].join('-')
    end

    # since I was having trouble bending the has_one to my will (specifically, allowing for only
    # delete/create/replace operations on it), I opted to use (has_many, limit: 1), so this will
    # return that one record (or nil), using the singular name.
    def business_filing
      business_filings.first
    end

    def primary_location_name
      locations.first.try(:name)
    end

    def in_business_since=(string)
      if year = string.presence.try{|s| s = s.to_i; s > 1700 ? s : nil }
        date = Date.new(year)
      else
        date = nil
      end
      write_attribute(:in_business_since, date)
    end

    def phone_numbers
      Hash.new.tap do |numbers|
        numbers[:phone_main]   = phone_main   if phone_main?
        numbers[:phone_mobile] = phone_mobile if phone_mobile?
        numbers[:phone_fax]    = phone_fax    if phone_fax
      end
    end

    def all_licenses
      self.business_licenses + self.personal_licenses
    end

  private

    # the form simply hides the insurance fields when the user says "No". this will actually nullify
    # the respective collumns unless #insured is truthy
    def nullify_insurance_fields_if_necessary
      return if self[:insured]
      self[:insurance_state_id]    = nil
      self[:insurance_valid_from]  = nil
      self[:insurance_valid_until] = nil
      self.insurance_certificate = nil
      return true
    end

    def set_active_flag
      self[:active] = can_be_activated?
      return true
    end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  respond_to :html, :json, :yaml

  load_and_authorize_resource

  attr_accessor :company, :markets, :categories

  before_filter CompaniesFilters::SetUpMarkets, CompaniesFilters::SetUpCategories, only: [:edit, :update]

  layout 'companies'

  def edit
    @company = Company.find(params[:id])
    respond_to do |format|
      format.html {
        render(%w[listing capabilities credentials].grep(params['section']).first || 'edit')
      }
    end
  end

  def update
    if @company.update_attributes(params[:company])
      redirect_to @company
    else
      respond_to do |format|
        format.html {
          render('edit')
        }
      end
    end
  end

end

app/helpers/company_helper.rb
module CompanyHelper

  def service_areas_partial_only_collection
    { false => t('service_areas.partial_only.false'),
      true =>  t('service_areas.partial_only.true') }.to_a
  end

  def dom_class_for_search_result(company)
    dom_class = []
    dom_class << :inactive unless company.active && company.visible
  end

  def edit_company_section_path(company, section)
    case section
    when :listing, :capabilities, :credentials
      edit_company_path(company, section: section)
    when :discounts
      company_discounts_path(company)
    end
  end

end

app/views/companies/_affiliations.haml
= form.simple_fields_for :affiliations do |affiliation|
  %ul[affiliation.object]
    %li.actions
      = include_remove_link

    = render 'affiliations/fields', builder: affiliation

.actions
  = include_add_link

  %script.template{type: 'text/html'}
    - cache 'company_affiliation_fields_template' do
      = form.simple_fields_for :affiliations, Affiliation.new, child_index: '_ID_' do |new_affiliation|
        %ul[new_affiliation.object]
          %li.actions
            = include_remove_link

          = render 'affiliations/fields', builder:  new_affiliation

app/views/companies/_capabilities_fieldsets.haml
= fieldset :description do

  %ul
    = form.input :description
    = form.input :benefits
    = form.input :specialty

= fieldset :service_areas do
  = render 'service_areas', form: form

= fieldset :service_categories do
  = render 'service_categories', form: form

= fieldset :operations do
  %ul
    = form.input :offers_24_hour_service,   as: :radio_buttons
    = form.input :offers_emergency_service, as: :radio_buttons

app/views/companies/_certifications.haml
= form.simple_fields_for :certifications do |certification|
  %ul[certification.object]
    %li.actions
      = include_remove_link

    = render 'certifications/fields', builder: certification

.actions
  = include_add_link

  %script.template{type: 'text/html'}
    - cache 'company_certification_fields_template' do
      = form.simple_fields_for :certifications, Certification.new, child_index: '_ID_' do |new_certification|
        %ul[new_certification.object]
          %li.actions
            = include_remove_link
          = render 'certifications/fields', builder:  new_certification

app/views/companies/_company.haml
%li[company]{class: dom_class_for_search_result(company)}

  %h3= company.name
  .arrow

  -# This is in a <script> to defer loading it into the DOM until it's selected. This makes for faster page-load times, but slightly less responsiveness when selecting a result (that assumes a move operation; before I made this change, I was creating new nodes, anyway, so this switch is 100% an improvement)
  %script.details{type: 'text/html'}
    = render 'companies/profile', company: company

    - if current_user.is_a? Administrator
      .admin_panel
        - if company.active
          .tag.ok active
        - else
          .tag inactive

        - if company.visible
          .tag.ok visible
        - else
          .tag invisible

        .link= link_to '[Edit in Admin]', admin_company_path(company)

app/views/companies/_credentials_fieldsets.haml
= fieldset :insurance do
  = render 'insurance', form: form

= fieldset :licenses do
  = fieldset :business_licenses do
    = render 'business_licenses', form: form
  = fieldset :personal_licenses do
    = render 'personal_licenses', form: form

= fieldset :business_filing do
  = render 'business_filing', form: form

= fieldset :affiliations do
  = render 'affiliations', form: form

= fieldset :associations do
  = render 'associations', form: form

= fieldset :certifications do
  = render 'certifications', form: form

app/views/companies/_locations.haml
= form.simple_fields_for :locations do |location|
  %ul[location.object]
    %li.actions
      = include_remove_link
    = render 'locations/fields', builder: location
    .clear

.actions
  = include_add_link

  %script.template{type: 'text/html'}
    - cache 'company_location_fields_template' do
      = form.simple_fields_for :locations, Location.new, child_index: '_ID_' do |new_location|
        %ul[new_location.object]
          %li.actions
            = include_remove_link
          = render 'locations/fields', builder: new_location

app/views/companies/_personal_licenses.haml
= form.simple_fields_for :personal_licenses do |personal_license|
  %div[personal_license.object]
    = personal_license.hidden_field :_destroy, class: :destroy
    .actions
      = include_remove_link
    = render personal_license.object

.actions
  = include_add_link

  %script.template{type: 'text/html'}
    - cache 'company_personal_license_fields_template' do
      = form.simple_fields_for :personal_licenses, PersonalLicense.new, child_index: '_ID_' do |new_personal_license|
        %ul[new_personal_license.object]
          %li.actions
            = include_remove_link
          %h5 New License

          -# temporary, until the issuing state input is enabled
          = new_personal_license.input       :issuing_state_id, as: :hidden
          = new_personal_license.association :issuing_state,    disabled: true # disabled means it wont be sent
          = new_personal_license.input       :number

app/views/companies/_profile.haml
.tabs
  %ul.nav.tab_bar
    = list_of [:listing, :capabilities, :credentials, :discounts] do |label|
      = link_to t(".tab_names.#{label}"), "##{tab_id_for(company, label)}"
    %li= link_to t(".tab_names.reviews"), "##{tab_id_for(company, :reviews)}", class: 'disabled ui-state-disabled'

  %header
    %h2= company.name
    - if company.in_business_since?
      .in_business_since= t('.in_business_since', year: company.since)

    - if can? :edit, company
      .actions
        = include_edit_link edit_company_path(company, section: :listing)

  = cache [:companies, company.id, :profile] do

    = tab_for company, :listing do

      - if company.locations.any?
        = profile_section :locations do
          - company.locations.each do |location|
            = link_to_blank_tab(url_for_google_maps_search(location.to_s)) do
              = render location

      - if company.phone_numbers.any?
        = profile_section :phone_numbers do
          %ul
            - company.phone_numbers.each do |type, number|
              %li.phone_number{class: type}
                %label= Company.human_attribute_name(type) << ?:
                %span= format_as_phone_number(number)

      - if company.website_url? or company.email?
        = profile_section :online do
          - if company.website_url?
            .website
              %label= Company.human_attribute_name(:website_url) << ?:
              = company.website
          - if company.email?
            .email
              %label= Company.human_attribute_name(:email) << ?:
              = mail_to company.email




    = tab_for company, :capabilities do

      - if company.description?
        = profile_section :description do
          = company.description

      - if company.benefits?
        = profile_section :benefits do
          = simple_format company.benefits

      - if company.specialty?
        = profile_section :specialty do
          = simple_format company.specialty

      - if company.sub_categories.any?
        = profile_section :categories do
          %ul.categories
            - company.sub_categories.group_by(&:category).each do |category, sub_categories|
              %li[category]
                %h4= category.name
                %ul.sub_categories
                  - sub_categories.each do |sub_cat|
                    %li[sub_cat]= sub_cat.name

      - if company.service_areas.any?
        = profile_section :service_area do
          %ul.markets
            - company.service_areas.group_by(&:market).each do |market, service_areas|
              %li[market]
                %h4= market.name
                %ul.service_areas
                  - service_areas.each do |service_area|
                    %li[service_area]= service_area.name

      = profile_section :operations do
        .offers_24_hour_service
          %label= Company.human_attribute_name(:offers_24_hour_service) << ':'
          = company.offers_24_hour_service ? 'Yes' : 'No'
        .offers_emergency_service
          %label= Company.human_attribute_name(:offers_emergency_service) << ':'
          = company.offers_emergency_service ? 'Yes' : 'No'



    = tab_for company, :credentials do

      - if company.insured?
        = profile_section :insurance, skip_instructions: true do
          - if company.insurance_certificate?
            = attached_file_thumbnail(company, :insurance_certificate)
          .instructions= t('.section.insurance.instructions')
          .state= t('.section.insurance.insured_in', company_name: company.name, state_name: company.insurance_state_name)
          .valid= t('.section.insurance.valid', from: company.insurance_valid_from, to: company.insurance_valid_until)
          - if company.insurance_certificate?
            = attached_file_summary(company, :insurance_certificate)

      - if company.all_licenses.any?
        = profile_section :licensure do
          .licenses.accordion= render company.all_licenses

      - if company.business_filing.present?
        = profile_section :business_status do
          .licenses.accordion= render company.business_filing

      - [:affiliations, :associations, :certifications].each do |section|
        - if (associated = company.send(section)).any?
          = profile_section section do
            .accordion{class: section}= render associated



    = tab_for company, :discounts do
      - if company.discounts.not_expired.any?
        = profile_section :discounts do
          .accordion.discounts= render company.discounts.not_expired
      - else
        = t('.discounts.none_available', default: "There are no offers available at this time.")




    = tab_for company, :reviews do
      %strong NOTE:
      Home manager reviews coming soon!

app/views/companies/_service_areas.haml
-#
  %ul#markets_selection
    = simple_fields_for :market_selection do |m|
      = m.input :add_market, collection: @markets.keys

- @markets.each_pair do |market, company_service_areas|
  -# %div[market]{hidden_if(company_service_areas.all?(&:new_record?))}
  %div[market]

    -# .actions
      = include_collapse_link  :market
      = include_expand_link :market
      = include_remove_link :market

    %h4= market.name

    %ul.service_areas
      = form.simple_fields_for :company_service_areas, company_service_areas do |s|
        - csa = s.object
        %li[csa.service_area]
          = s.hidden_field :service_area_id

          = s.input :_destroy, as: :inverse_boolean, label: csa.service_area.name, input_html: {checked: !csa.new_record?, class: :destroy}, wrapper_tag: :span, label_html: {class: :name}
          = s.input :partial_only, collection: service_areas_partial_only_collection, as: :radio_buttons, label: false, label_method: :last, value_method: :first, wrapper_tag: :span, wrapper_html: {class: [:partial_only, (csa.new_record? ? 'hidden' : nil)]}

    .collapsed_summary
      %span This will contain the summary
      .hint= t('.markets.collapsed_explanation')

app/views/companies/_service_categories.haml
%ul.add_new_category
  = simple_fields_for :category_selection do |c|
    = c.input :add_category, as: :grouped_select,
        collection: Category.includes(:sub_categories), group_method: :sub_categories,
        group_label_method: :name, label_method: :name, value_method: :id

- @categories.each_pair do |category, company_categories|
  %div[category]{hidden_if(company_categories.all?(&:new_record?))}
    %h4= category.name
    %ul
      = form.simple_fields_for :company_categories, company_categories do |c|
        %li[c.object.sub_category]{hidden_if(c.object.new_record?)}
          = c.hidden_field :_destroy, class: :destroy # this class is for the JS to find it
          = c.hidden_field :sub_category_id, class: :sub_category_id

          %span= c.object.sub_category.name

          %span.actions= include_remove_link :sub_category
          .clear

app/views/companies/identity.haml
- title t('.title', company_name: @company.name)

= simple_form_for @company do |form|

  = render 'identity_fieldsets', form: form

  %fieldset.last#buttons
    = link_to t('helpers.cancel'), @company, class: :cancel
    = form.button :submit, class: :save

app/views/companies/new.haml.erb
%a{:href => "/companies/"} Return to Index
%h2 Create Company
%fieldset.new_company
  %input#form_destination{:type => "hidden", :value => "/companies/"}/
  = render :partial => 'form', :locals => { :company => @company }

app/views/companies/search.haml.erb
/ This is the template for displaying companies, data's inserted by javascript
%script#company_template{:type => "text/x-jquery-tmpl"}
  <li class="company">
  <input type="hidden" class="company_id" value="${company.id}"/>
  <span class="company_name">${company.name}</span>
  <span class="company_address">
  ${company.address_1}{{if company.address_2}} ${company.address_2}{{/if}}, ${company.city}, ${company.state}, ${company.zip_code}
  </span>
  <span class="company_phone_number">${company.main_phone_number}</span>
  <span class="company_web_site">${company.web_site}</span>
  </li>
%h1 Provider Search
%div
  %form.companies_search{:action => "/companies/search_json", :method => "GET"}
    %input#company_name{:name => "company_name", :type => "text"}/
    %img.loading_graphic.hidden{:alt => "Loading...", :src => "/images/loading_small.gif"}/
%ul.companies_index_search
.companies_index_search_no_data_template.hidden
  .no_data
    %h1 No Companies Found
    %p We couldn't locate any matching companies.  Please try a broader search.
.company_show
.company_show_no_data_template.hidden
  .no_data
    %h1 No Company Selected
    %p Please select a company on the left to view its details.

app/views/companies/service.haml
- title t('.title', company_name: @company.name)

= simple_form_for @company do |form|

  = render 'service_fieldsets', form: form

  %fieldset.last#buttons
    = link_to t('helpers.cancel'), @company, class: :cancel
    = form.button :submit, class: :save