config/routes.rb
require 'sidekiq/web'

ServiceProviderPortal::Application.routes.draw do

  ActiveAdmin.routes(self)

  resources :search, only: :index

  resources :companies, only: [:show, :edit, :update] do
    resources :alerts
    resources :discounts
    resources :users
    resources :company_admins, path: 'users', controller: :users
    resources :administrators, path: 'users', controller: :users
  end

  resource  :account, only: [:show, :edit, :update]

  resources :password_resets, only: [:new, :create, :show, :update],
    constraints: { id: /[a-zA-Z0-9\-_]{12}/ }
  resources :activate, only: [:new, :create, :show, :update], controller: :user_activation,
    constraints: { id: /[a-zA-Z0-9\-_]{12}/ }

  resource :session, only: [:create]

  scope controller: :sessions do
    get :login,  action: :new,     as: :login
    get :logout, action: :destroy, as: :logout
  end

  constraints(proc { |req| uid = req.session[:user_id] and User.find(uid).is_a?(Administrator) }) do
    get '/debug/:action', controller: :debug
    mount Sidekiq::Web => '/sidekiq'
  end

  scope '/follow_us_on', as: :follow_us_on do
    get 'twitter',  to: redirect('https://twitter.com/#!/trustmaster')
    get 'facebook', to: redirect('https://www.facebook.com/pages/Trust-Master/165946716770592')
  end


  root :to => 'search#index'

  get '*slug', controller: :pages, action: :show, as: :page, constraints: RoutingConstraints::Pages
end

app/controllers/accounts_controller.rb
class AccountsController < InheritedResources::Base
  defaults resource_class: User, collection_name: :users, instance_name: :user
  actions :edit, :update
  acts_as_singleton!
  load_and_authorize_resource :user

  layout 'account'

  respond_to :html, :json

  def update
    update!(notice: t('accounts.saved'))
  end

  def edit
    super do |format|
      format.html {
        render(%w[basic notifications privacy].grep(params['section']).first || 'edit')
      }
    end
  end

  protected

  def resource
    current_user
  end
end

app/views/accounts/basic.haml
- title t('.title')

= simple_form_for resource, url: account_path do |f|
  = fieldset :name do
    %ul.horizontal
      = f.input :first_name
      = f.input :middle_name, input_html: { maxlength: 3 }, wrapper_html: { class: :short }
      = f.input :last_name

  = fieldset :contact do
    %ul
      = f.input :email
      = f.input :phone, input_html: { value: format_as_phone_number(f.object.phone) }

  -# Fixme!
    = fieldset :password do
      %ul
        = f.input :old_password
        = f.input :password
        = f.input :password_confirmation

  = fieldset :buttons, show_header: false do
    = link_to t('helpers.cancel'), :back, class: :cancel
    = f.button :submit, class: :save

app/views/accounts/edit.haml
Edit

app/views/accounts/notifications.haml
- title t('.title')

%h4= t('.coming_soon')

-#
  = simple_form_for resource, url: account_path(resource) do |f|
    = fieldset :main, false do
      %ul
        = f.input :notification_emails

    = fieldset :buttons, false do
      = link_to t('helpers.cancel'), :back, class: :cancel
      = f.button :submit, class: :save

app/views/accounts/privacy.haml
- title t('.title')

%h4= t('.coming_soon')

-#
  = simple_form_for resource, url: account_path(resource) do |f|
    = fieldset :other do
      %ul
        = f.input :about_me
        = f.input :avatar

    = fieldset :contact do
      %ul
        = f.input :email
        = f.input :location

    = fieldset :buttons, false do
      = link_to t('helpers.cancel'), :back, class: :cancel
      = f.button :submit, class: :save